# 是否启用插件自带的日志器
# 启用将会把日志打印到控制台上
usePluginLogger: false

# 是否启用调试信息输出
debug: false

# 是否保存至文件
logSaveToFile: true

# 缓存输出（一般在需要调试时才会改为false）
# 启用则日志可能会延迟输出到文件中，优化性能
# 关闭则日志输出时立即保存至文件，但性能较差
bufferWriter: true

# 日志文件最多保存多少天
# 设置为小于 1 的值将会让日志永远不会被自动删除
saveDays: 7

# 日志时间前缀的格式
dateFormat: "yyyy-MM-dd HH:mm:ss:SSS"


####################################################################################
#
# logFolder: 日志集中存储的位置
#
# 若不设置该值，则日志将会存储在 plugins/插件名/logs 文件夹下
# 若设置了该值，则日志将会存储在 logFolder 设定值的文件夹中
# 自动判断 绝对路径 与 相对路径
#
####################################################################################
#
# 注意YAML语法:
# 反斜杠将会与后一个字构成特殊字符，使用双反斜杠 \\ 才能代表一个反斜杠
# 因此，若你的路径为 D:\Logs 则请填写 D:\\logs
# 或者使用 D:/logs 也可以代替 D:\\logs
#
####################################################################################

# 建议 Windows 集群服务器使用该设定
# 日志存储在 D:/logs/插件名 文件夹下
# logFolder: "D:/logs"

# 建议 Linux 集群服务器使用该设定
# 日志存储在 /data/logs/插件名 文件夹下
# logFolder: "/data/logs"

# 建议单端服务器使用该设定
# 日志存储在 服务端根目录/logs/plugins/插件名 文件夹下
logFolder: "logs/plugins"
