name: HamsterAPI
version: ${version}
main: cn.hamster3.api.HamsterAPI
authors: [Hamster3]
description: 一个方便开发者使用的API
website: https://www.hamster3.cn/

load: STARTUP
api-version: "1.16"

softdepend:
  - Vault
  - PlayerPoints

commands:
  HamsterAPI:
    aliases: [hapi]
    description: HamsterAPI主要命令
    permission: hapi.use
    permission-message: §c您没有这个权限

permissions:
  hapi.use:
    default: op